export default [
    { url: 'https://www.defacto.com.tr/statik/sitemap', selector: '.page-body-content-sitemap a',pageSelector:".catalog-products" },



    { url: 'https://www.abiyefon.com/', selector: '#topMainMenu a',pageSelector:'.products' },
    { url: 'https://www.addax.com.tr/', selector: '#MainMenu a', pageSelector:'.Prd' },
    { url: 'https://www.adidas.com.tr/tr', selector: '[data-auto-id="main-menu"] a' },
    { url: 'https://www.adl.com.tr/', selector: '.navigation a',pageSelector:'.products__items' },
    { url: 'https://alinderi.com.tr/', selector: '#cbp-hrmenu a',pageSelector:'.js-product-miniature-wrapper' },
    { url: 'https://www.alpinist.com.tr/', selector: '#navigation a',pageSelector:'.showcase-container' },
    { url: 'https://www.armine.com/', selector: '.navigation a',pageSelector:'#ProductPageProductList' },
    { url: 'https://www.avva.com.tr/', selector: '.navigation a',pageSelector:'.productItem' },
    { url: 'https://www.bagmori.com/', selector: '.HorizontalList  a',pageSelector:'.ProductList' },
    { url: 'https://www.bambiayakkabi.com.tr/', selector: '#divUcTopMenu a',pageSelector:'.productItem' },
  //  { url: 'https://www.baqa.com.tr/', selector: '.navigation a',pageSelector:'.ItemOrj.col-3' },
    { url: 'https://www.bershka.com/tr/h-woman.html', selector: '.menu-desktop__nav a',pageSelector:'.category-product-card' },
    { url: 'https://www.beymen.com/home/sitemap', selector:'.m-subNav .m-subNav__item a.m-subNav__link', pageSelector:'#productList' },
    { url: 'https://www.beymenclub.com/kadin-30058',selector:'a.m-subNav__link', pageSelector:'#productList' },
    { url: 'https://www.beymenclub.com/erkek-30060',selector:'a.m-subNav__link', pageSelector:'#productList' },
   { url: 'https://www.beyyoglu.com/kadin/',selector:'list__header-categories a', pageSelector:'.js-product-wrapper.product-item' },
   { url: 'https://www.beyyoglu.com/erkek/',selector:'.list__header-categories a', pageSelector:'.js-product-wrapper.product-item' },
   { url: 'https://www.blacknoble.com/erkek?currency=try',selector:'.navigation a', pageSelector:'.productItem' },
   { url: 'https://www.bsl.com.tr/tr/site-haritasi',selector:'.SitemapMenu a', pageSelector:'.Prd' },
   { url: 'https://www.butigo.com.tr/',selector:'.navigation a', pageSelector:'[data-gtm-product]' },
   { url: 'https://www.bysaygi.com/',selector:'.navigation a', pageSelector:'.productItem' },
   { url: 'https://www.centone.com.tr/',selector:'.main-nav a', pageSelector:'.product-item' },
 //  { url: 'https://www.colins.com.tr/',selector:'#defaultmenu a', pageSelector:'.productbox.clearfix.list-item' },
 { url: 'https://www.dericeket.com.tr/',selector:'.navigation a', pageSelector:'.productItem' },
 { url: 'https://www.dericlub.com.tr/',selector:'.navigation a', pageSelector:'.ItemOrj' },
 { url: 'https://www.deriderim.com/',selector:'.navigation a', pageSelector:'#ProductPageProductList' },
 { url: 'https://derimod.com.tr/collections/erkek-anasayfa?filter.v.availability=1',selector:'.site-header div.items-center a', pageSelector:'.ProductCard' },
 { url: 'https://derimod.com.tr/collections/kadin-anasayfa?filter.v.availability=1',selector:'.site-header div.items-center a', pageSelector:'.ProductCard' },
 { url: 'https://www.deristore.com.tr/',selector:'.megamenu-pattern a', pageSelector:'.product' },
 { url: 'https://www.desa.com.tr/kadin/',selector:'.category-container a', pageSelector:'.product-item-box' },
 { url: 'https://www.desa.com.tr/erkek/',selector:'.category-container a', pageSelector:'.product-item-box' },
 { url: 'https://www.dilvin.com.tr/',selector:'.nav.navbar-nav a', pageSelector:'.product' },
 { url: 'https://www.divarese.com.tr/',selector:'.navbar__content a', pageSelector:'.products__item' },
 { url: 'https://www.dogostore.com/',selector:'nav ul.menu a', pageSelector:'#mainColumn' },
 { url: 'https://www.elleshoes.com/kadin',selector:'.kategoriLink a', pageSelector:'.productItem' },
 { url: 'https://www.elleshoes.com/erkek',selector:'.kategoriLink a', pageSelector:'.productItem' },
 { url: 'https://www.elleshoes.com/kadin-deri-ceket',selector:'.kategoriLink a', pageSelector:'.productItem' },
 { url: 'https://www.elleshoes.com/erkek-deri-ceket',selector:'.kategoriLink a', pageSelector:'.productItem' },
 { url: 'https://exquise.com/',selector:'nav a', pageSelector:'.product-list article' },
 { url: 'https://www.fashionfriends.com/',selector:'.navigation a', pageSelector:'.ItemOrj' },
 { url: 'https://www.gizia.com',selector:'#mainMenu a', pageSelector:'#mainColumn' },
 { url: 'https://www2.hm.com/tr_tr/productpage.1135056011.html',selector:'nav a', pageSelector:'.product-item' },
 { url: 'https://www.hotic.com.tr/',selector:'nav.navbar a', pageSelector:'.item-grid' },
 { url: 'https://ikbalderi.com/',selector:'.nav a', pageSelector:'.products' },
 { url: 'https://www.ipekyol.com.tr/',selector:'.menu.main-menu a', pageSelector:'[data-product-id]' },
 { url: 'https://www.jimmykey.com/tr/',selector:'nav#MainMenu a', pageSelector:'.Prd' },
 { url: 'https://www.kigili.com/',selector:'.navigation a', pageSelector:'.product-item-wrapper' },
 { url: 'https://tr.kikiriki.com/',selector:'.main-menu a', pageSelector:'.product-list-item' },
 { url: 'https://www.kipling.com.tr/',selector:'ul.new-main-menu a', pageSelector:'.product.product--zoom' },
 { url: 'https://www.koton.com/site-haritasi',selector:'.site-map__list a', pageSelector:'.product-item__body' },
 { url: 'https://www.lacht.com.tr/',selector:'section.menu a', pageSelector:'.card-product' },
 { url: 'https://www.lcwaikiki.com/tr-TR/TR/site-haritasi', selector: '.sitemap a', pageSelector:'.product-grid' },
 //{ url: 'https://www.levis.com.tr/', selector: '.main-links a', pageSelector:'[data-js="p-item"]' },
 { url: 'https://www.lovemybody.com.tr/', selector: '.navigation a', pageSelector:'.product-item-box',selectorHover:'.mobile-navigation-icon',action:'hover' },
 { url: 'https://www.machka.com.tr/', selector: '.no-sub a', pageSelector:'.category-title',selectorHover:'.modal-body ul [href="javascript:void(0);"]',action:'click' },
 { url: 'https://shop.mango.com/tr/sitemap', selector: 'a.site-map-item', pageSelector:'.catalog' },
 { url: 'https://www.manuka.com.tr/', selector: '#mainMenu a', pageSelector:'.catalogWrapper' },
 { url: 'https://www.markapia.com/', selector: 'div.items-center a', pageSelector:'.catalogWrapper' },
 { url: 'https://www.matras.com/', selector: '.open-sub a', pageSelector:'.product_box' },
 { url: 'https://www.mavi.com/site-haritasi', selector: 'a', pageSelector:'.product-list-cards' },
 { url: 'https://miostil.com/', selector: '.mobile-menu.dropdown-menu a', pageSelector:'.product-grid' },
 { url: 'https://www.network.com.tr/', selector: '.navbar a', pageSelector:'#products' },
 { url: 'https://www.nike.com/', selector: '.pre-desktop-menu a', pageSelector:'.product-card' },
 { url: 'https://www.nu.com.tr/', selector: '.main-navigation a', pageSelector:'#CollectionProductGrid' },
 //{ url: 'https://olegcassini.com.tr/', selector: '.nav-links a', pageSelector:'[data-id]' },
 { url: 'https://www.oxxo.com.tr/', selector: '#MainMenu a', pageSelector:'.ProductList' },
 { url: 'https://www.panco.com.tr/', selector: '.navigation a', pageSelector:'.js-list-products' },
 { url: 'https://www.penti.com/tr/', selector: '.sub a', pageSelector:'.products' },
 { url: 'https://www.perspective.com.tr/', selector: '#MainMenu a', pageSelector:'.ProductList' },
 { url: 'https://www.pierrecardin.com.tr', selector: '.header__navigation a', pageSelector:'.product__listing' },
 { url: 'https://tr.puma.com/site-haritasi', selector: '.sitemap a', pageSelector:'.products-grid' },
 { url: 'https://quzu.com.tr/', selector: '.menu-list a', pageSelector:'.product-grid' },
 { url: 'https://www.roman.com.tr/', selector: '#main-menu a', pageSelector:'.product-detail-card' },
 { url: 'https://sarar.com/', selector: '#mainMenu a', pageSelector:'.catalogWrapper' },
]

