export default [
    { url: 'https://www.defacto.com.tr/statik/sitemap', selector: '.page-body-content-sitemap a',imageSelector:'.product-card a img' },
    { url: 'https://www.koton.com/site-haritasi', selector: '.site-map__box a' },
    { url: 'https://www.lcwaikiki.com/tr-TR/TR/site-haritasi', selector: '.sitemap a' },

    { url: 'https://www.abiyefon.com/', selector: '#topMainMenu a' },
    { url: 'https://www.addax.com.tr/', selector: '#MainMenu a' },
    { url: 'https://www.adidas.com.tr/tr', selector: '[data-auto-id="main-menu"] a' },
    { url: 'https://www.adl.com.tr/', selector: '.navigation a' },
    { url: 'https://alinderi.com.tr/', selector: '#cbp-hrmenu a' },
    { url: 'https://www.alpinist.com.tr/', selector: '#navigation a' },
    { url: 'https://www.armine.com/', selector: '.navigation a' },
    { url: 'https://www.avva.com.tr/', selector: '.navigation a' },
    { url: 'https://www.bagmori.com/', selector: '.HorizontalList  a' },
    { url: 'https://www.bambiayakkabi.com.tr/', selector: '#divUcTopMenu a' },
    { url: 'https://www.baqa.com.tr/', selector: '.navigation a' },
    { url: 'https://www.bershka.com/tr/h-woman.html', selector: '.menu-desktop__nav a' },
    //{ url: '', selector: '' },
//    { url: '', selector: '' },
//    { url: '', selector: '' },
]