export default [
    { url: 'https://www.defacto.com.tr/statik/sitemap', selector: '.page-body-content-sitemap a',pageSelector:".catalog-products" },
    { url: 'https://www.koton.com/site-haritasi', selector: '.site-map__box a',imageSelector:"picture img" },
    { url: 'https://www.lcwaikiki.com/tr-TR/TR/site-haritasi', selector: '.sitemap a' },

    { url: 'https://www.abiyefon.com/', selector: '#topMainMenu a',pageSelector:'.products' },
    { url: 'https://www.addax.com.tr/', selector: '#MainMenu a', pageSelector:'.Prd' },
    { url: 'https://www.adidas.com.tr/tr', selector: '[data-auto-id="main-menu"] a' },
    { url: 'https://www.adl.com.tr/', selector: '.navigation a',pageSelector:'.products__items' },
    { url: 'https://alinderi.com.tr/', selector: '#cbp-hrmenu a',pageSelector:'.js-product-miniature-wrapper' },
    { url: 'https://www.alpinist.com.tr/', selector: '#navigation a',pageSelector:'.showcase-container' },
    { url: 'https://www.armine.com/', selector: '.navigation a',pageSelector:'#ProductPageProductList' },
    { url: 'https://www.avva.com.tr/', selector: '.navigation a',pageSelector:'.productItem' },
    { url: 'https://www.bagmori.com/', selector: '.HorizontalList  a',pageSelector:'.ProductList' },
    { url: 'https://www.bambiayakkabi.com.tr/', selector: '#divUcTopMenu a',pageSelector:'.productItem' },
    { url: 'https://www.baqa.com.tr/', selector: '.navigation a',pageSelector:'.ItemOrj.col-3' },
    { url: 'https://www.bershka.com/tr/h-woman.html', selector: '.menu-desktop__nav a' },
    //{ url: '', selector: '' },
//    { url: '', selector: '' },
//    { url: '', selector: '' },
]