name: tozlu
on:
  schedule:
    - cron:  '0 0 * * 6,1'
env:
  GH_TOKEN: ${{secrets.GH_TOKEN}}
jobs:
  kadin_job:
    uses: ./.github/workflows/reusable.yml
    with:
      GENDER: all
      maxconcurrency: '5'
      WEBSITE: 'biraradamoda'
      marka: 'tozlu'
    secrets: inherit
